export function baseTemplate(content: string, storeName: string = "Sales Agent"): string {
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f5;padding:24px 0;">
    <tr><td align="center">
      <table role="presentation" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.06);">
        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#059669,#10b981);padding:28px 32px;text-align:center;">
            <h1 style="color:#fff;font-size:20px;font-weight:800;margin:0;letter-spacing:-0.5px;">${storeName}</h1>
            <p style="color:rgba(255,255,255,0.8);font-size:12px;margin:4px 0 0;font-weight:600;text-transform:uppercase;letter-spacing:1px;">AI Sales Agent</p>
          </td>
        </tr>
        <!-- Content -->
        <tr><td style="padding:32px;">${content}</td></tr>
        <!-- Footer -->
        <tr>
          <td style="padding:20px 32px;border-top:1px solid #e4e4e7;text-align:center;">
            <p style="color:#a1a1aa;font-size:11px;margin:0;">Generated by your WhatsApp AI Sales Agent</p>
            <p style="color:#d4d4d8;font-size:10px;margin:4px 0 0;">This is an automated message. Do not reply.</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

export function backupEmailContent(manifest: { timestamp: string; tableCount: number; totalRows: number; tables: { name: string; rows: number }[] }): string {
  const rows = manifest.tables.map(t =>
    `<tr><td style="padding:8px 12px;border-bottom:1px solid #e4e4e7;color:#18181b;font-size:13px;">${t.name}</td><td style="padding:8px 12px;border-bottom:1px solid #e4e4e7;color:#18181b;font-size:13px;text-align:right;font-weight:600;">${t.rows.toLocaleString()}</td></tr>`
  ).join("");
  return `
    <div style="text-align:center;margin-bottom:24px;">
      <div style="width:56px;height:56px;background:#ecfdf5;border-radius:16px;display:inline-flex;align-items:center;justify-content:center;margin-bottom:12px;">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#10b981" stroke-width="2"><path d="M12 2l3 7h7l-5.5 4 2 7L12 16l-5.5 4 2-7L3 9h7z"/></svg>
      </div>
      <h2 style="color:#18181b;font-size:18px;font-weight:800;margin:0 0 4px;">Backup Successful</h2>
      <p style="color:#71717a;font-size:13px;margin:0;">${manifest.timestamp}</p>
    </div>
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;border-radius:12px;padding:16px;margin-bottom:24px;">
      <tr><td style="padding:4px 8px;font-size:12px;color:#71717a;">Tables</td><td style="padding:4px 8px;font-size:14px;font-weight:700;color:#18181b;text-align:right;">${manifest.tableCount}</td></tr>
      <tr><td style="padding:4px 8px;font-size:12px;color:#71717a;">Total Rows</td><td style="padding:4px 8px;font-size:14px;font-weight:700;color:#18181b;text-align:right;">${manifest.totalRows.toLocaleString()}</td></tr>
    </table>
    <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
      <thead><tr style="background:#f8f9fa;"><th style="padding:8px 12px;text-align:left;font-size:11px;color:#71717a;text-transform:uppercase;letter-spacing:0.5px;">Table</th><th style="padding:8px 12px;text-align:right;font-size:11px;color:#71717a;text-transform:uppercase;letter-spacing:0.5px;">Rows</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
}

export function reportEmailContent(data: { revenue: number; cost: number; profit: number; orderCount: number; from: string; to: string }): string {
  return `
    <div style="text-align:center;margin-bottom:24px;">
      <h2 style="color:#18181b;font-size:18px;font-weight:800;margin:0 0 4px;">Sales Report</h2>
      <p style="color:#71717a;font-size:13px;margin:0;">${data.from} — ${data.to}</p>
    </div>
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">
      <tr>
        <td style="width:33%;text-align:center;background:#f0fdf4;border-radius:12px;padding:16px;">
          <p style="font-size:11px;color:#16a34a;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 4px;">Revenue</p>
          <p style="font-size:20px;font-weight:800;color:#16a34a;margin:0;">PKR ${data.revenue.toLocaleString()}</p>
        </td>
        <td style="width:33%;text-align:center;background:#fef2f2;border-radius:12px;padding:16px;">
          <p style="font-size:11px;color:#dc2626;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 4px;">Cost</p>
          <p style="font-size:20px;font-weight:800;color:#dc2626;margin:0;">PKR ${data.cost.toLocaleString()}</p>
        </td>
        <td style="width:33%;text-align:center;background:#eff6ff;border-radius:12px;padding:16px;">
          <p style="font-size:11px;color:#2563eb;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;margin:0 0 4px;">Profit</p>
          <p style="font-size:20px;font-weight:800;color:#2563eb;margin:0;">PKR ${data.profit.toLocaleString()}</p>
        </td>
      </tr>
    </table>
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;border-radius:12px;padding:16px;">
      <tr><td style="padding:4px 8px;font-size:12px;color:#71717a;">Orders</td><td style="padding:4px 8px;font-size:14px;font-weight:700;color:#18181b;text-align:right;">${data.orderCount}</td></tr>
      <tr><td style="padding:4px 8px;font-size:12px;color:#71717a;">Avg Order Value</td><td style="padding:4px 8px;font-size:14px;font-weight:700;color:#18181b;text-align:right;">PKR ${data.orderCount > 0 ? Math.round(data.revenue / data.orderCount).toLocaleString() : 0}</td></tr>
    </table>`;
}

export function invoiceEmailContent(order: { id: string; customerName?: string; productName?: string; amount: number; status: string }): string {
  return `
    <div style="text-align:center;margin-bottom:24px;">
      <div style="width:56px;height:56px;background:#fef3c7;border-radius:16px;display:inline-flex;align-items:center;justify-content:center;margin-bottom:12px;">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#f59e0b" stroke-width="2"><path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
      </div>
      <h2 style="color:#18181b;font-size:18px;font-weight:800;margin:0 0 4px;">Invoice #${order.id.slice(-8)}</h2>
      <p style="color:#71717a;font-size:13px;margin:0;">${order.customerName || "Valued Customer"}</p>
    </div>
    <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin-bottom:16px;">
      <tr><td style="padding:10px 12px;border-bottom:1px solid #e4e4e7;font-size:13px;color:#71717a;">Product</td><td style="padding:10px 12px;border-bottom:1px solid #e4e4e7;font-size:13px;font-weight:600;color:#18181b;text-align:right;">${order.productName || "N/A"}</td></tr>
      <tr><td style="padding:10px 12px;border-bottom:1px solid #e4e4e7;font-size:13px;color:#71717a;">Status</td><td style="padding:10px 12px;border-bottom:1px solid #e4e4e7;font-size:13px;font-weight:600;color:#18181b;text-align:right;">${order.status}</td></tr>
      <tr><td style="padding:10px 12px;font-size:13px;color:#71717a;">Total</td><td style="padding:10px 12px;font-size:18px;font-weight:800;color:#059669;text-align:right;">PKR ${order.amount.toLocaleString()}</td></tr>
    </table>`;
}
